In [2]:
import numpy as np
import pandas as pd

#colnames=['grab_table', 'which_stations', 'dest_1', 'dest_2', 'dest_3', 'dest_4', 'dest_5', 'dest_6','dest_7', 'dest_8', 'dest_9', 'dest_10', 'dest_11', 'dest_12', 'dest_13', 'leave_line', 'leave_line_stations', 'planning_for_refill', 'refill_stations'] 
survey_data = pd.read_csv("C:/Users/akabo/Downloads/Ducling project/Ducling Survey Cleaned.csv", header=0, sep = ",")
#survey_data.colnames=['grab_table', 'which_stations', 'dest_1', 'dest_2', 'dest_3', 'dest_4', 'dest_5', 'dest_6','dest_7', 'dest_8', 'dest_9', 'dest_10', 'dest_11', 'dest_12', 'dest_13', 'leave_line', 'leave_line_stations', 'planning_for_refill', 'refill_stations']

In [3]:
survey_data.head()

,Grab table?,Which Stations?,1st Destination,2nd Destination,3rd Destination,4th Destination,5th Destination,6th Destination,7th Destination,8th Destination,...,12th Destination,13th Destination,Leave line?,"If Yes, which station(s)?",More food?,If Yes,eat,mm,Unnamed: 21,Unnamed: 22
0,No,"Water/Juices,Drinks",Drinks,Water/Juices,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,No,NaN,Yes,Pizza,NaN,NaN,NaN,NaN
1,Yes,"Global Market,Grill,Water/Juices,Drinks",Grill,Global Market,Drinks,Water/Juices,NaN,NaN,NaN,NaN,...,NaN,NaN,No,NaN,Yes,Grill,Pizza,NaN,NaN,NaN
2,Yes,"Family Meal,Global Market,Salad Bar,Water/Juic...",Family Meal,Global Market,Salad Bar,Fruit,Water/Juices,Drinks,NaN,NaN,...,NaN,NaN,Yes,"Grill,Pizza",Yes,Desserts,NaN,NaN,NaN,NaN
3,No,"Special,Salad Bar",Special,Salad Bar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,No,NaN,Yes,Desserts,NaN,NaN,NaN,NaN
4,Yes,"Family Meal,Pizza,Gluten Free,Water/Juices,Des...",Water/Juices,Gluten Free,Pizza,Family Meal,Desserts,NaN,NaN,NaN,...,NaN,NaN,No,NaN,No,Pizza,NaN,NaN,NaN,NaN

In [8]:
a=survey_data.groupby(["1st Destination","2nd Destination"]).size().to_frame('First').reset_index()
b=a["1st Destination"]=="Bread"
c= a.loc[b]
c

  1st Destination 2nd Destination  First
0           Bread     Family Meal      2
1           Bread       Salad Bar      1
2           Bread           Soups      1
3           Bread           Vegan      1

In [11]:
prob = [['First', 'Second']]
for i in range(2,12):
        prob = np.append(prob, survey_data.iloc[:,i:i+2].values,axis=0)
prob                     

#df = pd.DataFrame(prob).reset_index()
#df

array([['First', 'Second'],
       ['Drinks', 'Water/Juices'],
       ['Grill', 'Global Market'],
       ...,
       [nan, nan],
       [nan, nan],
       [nan, nan]], dtype=object)

In [15]:
prob = pd.DataFrame(prob[1:],columns=["First","Second"])
prob

              First         Second
0            Drinks   Water/Juices
1             Grill  Global Market
2       Family Meal  Global Market
3           Special      Salad Bar
4      Water/Juices    Gluten Free
5             Grill          Fruit
6             Grill   Water/Juices
7       Family Meal          Grill
8             Grill    Family Meal
9         Salad Bar          Grill
10     Water/Juices    Family Meal
11            Pizza            NaN
12            Pizza  Global Market
13          Special      Salad Bar
14            Pizza          Grill
15        Salad Bar  Global Market
16            Grill         Drinks
17      Gluten Free          Soups
18          Special          Grill
19            Grill            NaN
20    Global Market   Water/Juices
21          Special          Grill
22        Salad Bar          Vegan
23            Vegan    Family Meal
24            Grill      Salad Bar
25    Global Market            NaN
26        Salad Bar    Gluten Free
27        Salad Bar        Special
28            Grill  Global Market
29    Global Market    Family Meal
...             ...            ...
2530            NaN            NaN
2531            NaN            NaN
2532            NaN            NaN
2533            NaN            NaN
2534            NaN            NaN
2535            NaN            NaN
2536            NaN            NaN
2537            NaN            NaN
2538            NaN            NaN
2539            NaN            NaN
2540            NaN            NaN
2541            NaN            NaN
2542            NaN            NaN
2543            NaN            NaN
2544            NaN            NaN
2545            NaN            NaN
2546            NaN            NaN
2547            NaN            NaN
2548            NaN            NaN
2549            NaN            NaN
2550            NaN            NaN
2551            NaN            NaN
2552            NaN            NaN
2553            NaN            NaN
2554            NaN            NaN
2555            NaN            NaN
2556            NaN            NaN
2557            NaN            NaN
2558            NaN            NaN
2559            NaN            NaN

[2560 rows x 2 columns]

In [24]:
prob['Second'] = prob['Second'].fillna('Table')
cool = prob.groupby(['First', 'Second']).size().to_frame('freq').reset_index()
a= prob.groupby('First').size().to_frame('denominator').reset_index()
b = pd.merge(cool, a, how = 'inner', on = 'First')
b['prob'] = b['freq']/b['denominator']
b

            First         Second  freq  denominator      prob
0           Bread    Family Meal     2           11  0.181818
1           Bread          Grill     1           11  0.090909
2           Bread      Salad Bar     3           11  0.272727
3           Bread          Soups     1           11  0.090909
4           Bread          Table     2           11  0.181818
5           Bread          Vegan     2           11  0.181818
6            Deli       Desserts     3           21  0.142857
7            Deli         Drinks     2           21  0.095238
8            Deli    Family Meal     1           21  0.047619
9            Deli          Fruit     2           21  0.095238
10           Deli          Grill     1           21  0.047619
11           Deli      Salad Bar     3           21  0.142857
12           Deli          Table     6           21  0.285714
13           Deli   Water/Juices     3           21  0.142857
14       Desserts           Deli     1           43  0.023256
15       Desserts         Drinks     1           43  0.023256
16       Desserts          Fruit     2           43  0.046512
17       Desserts      Salad Bar     1           43  0.023256
18       Desserts          Table    38           43  0.883721
19         Drinks          Bread     2           83  0.024096
20         Drinks           Deli     4           83  0.048193
21         Drinks       Desserts    10           83  0.120482
22         Drinks    Family Meal     1           83  0.012048
23         Drinks          Fruit     6           83  0.072289
24         Drinks  Global Market     1           83  0.012048
25         Drinks          Grill     1           83  0.012048
26         Drinks          Pizza     1           83  0.012048
27         Drinks      Salad Bar     2           83  0.024096
28         Drinks          Table    50           83  0.602410
29         Drinks   Water/Juices     5           83  0.060241
..            ...            ...   ...          ...       ...
144       Special          Pizza     6           55  0.109091
145       Special      Salad Bar    13           55  0.236364
146       Special          Soups     5           55  0.090909
147       Special          Table     8           55  0.145455
148       Special          Vegan     2           55  0.036364
149       Special   Water/Juices     3           55  0.054545
150         Vegan          Bread     1           27  0.037037
151         Vegan       Desserts     2           27  0.074074
152         Vegan         Drinks     1           27  0.037037
153         Vegan    Family Meal     2           27  0.074074
154         Vegan  Global Market     1           27  0.037037
155         Vegan    Gluten Free     3           27  0.111111
156         Vegan          Grill     2           27  0.074074
157         Vegan      Salad Bar     4           27  0.148148
158         Vegan          Soups     3           27  0.111111
159         Vegan        Special     2           27  0.074074
160         Vegan          Table     1           27  0.037037
161         Vegan   Water/Juices     5           27  0.185185
162  Water/Juices           Deli     3           82  0.036585
163  Water/Juices       Desserts     9           82  0.109756
164  Water/Juices         Drinks     8           82  0.097561
165  Water/Juices    Family Meal     3           82  0.036585
166  Water/Juices          Fruit     7           82  0.085366
167  Water/Juices  Global Market     1           82  0.012195
168  Water/Juices    Gluten Free     2           82  0.024390
169  Water/Juices          Grill     1           82  0.012195
170  Water/Juices          Pizza     3           82  0.036585
171  Water/Juices      Salad Bar     3           82  0.036585
172  Water/Juices        Special     1           82  0.012195
173  Water/Juices          Table    41           82  0.500000

[174 rows x 5 columns]

In [49]:
import csv

b.to_csv('b', sep=',', na_rep="NA", header=True, index=True)

In [15]:
survey_data_transformed = survey_data

In [81]:
survey_data.grab_table.value_counts()

Yes    161
No      95
Name: grab_table, dtype: int64

In [82]:
survey_data.grab_table.count()

256

In [83]:
grab_table_yes = sum(x=="Yes" for x in survey_data.grab_table)/survey_data.grab_table.count()
grab_table_yes

0.62890625

In [84]:
grab_table_no = 1- grab_table_yes
grab_table_no

0.37109375

In [16]:
survey_data.dest_1.value_counts()

AttributeError: 'DataFrame' object has no attribute 'dest_1'

In [86]:
print("Probability tr_fm: ", sum(x=="Family Meal" for x in survey_data.dest_1)/survey_data.dest_1.count())

Probability tr_fm:  0.22265625

In [88]:
for st in station_list:
    prob = sum(x==st for x in survey_data.dest_1)/survey_data.dest_1.count()
    print("Tray to "+ st + ": (Tr_" + st[:3] + ") " + str(prob))

Tray to Family Meal: (Tr_Fam) 0.22265625
Tray to Global Market: (Tr_Glo) 0.18359375
Tray to Grill: (Tr_Gri) 0.171875
Tray to Special: (Tr_Spe) 0.078125
Tray to Gluten Free: (Tr_Glu) 0.0703125
Tray to Salad Bar: (Tr_Sal) 0.0703125
Tray to Pizza: (Tr_Piz) 0.0703125
Tray to Vegan: (Tr_Veg) 0.03515625
Tray to Water/Juices: (Tr_Wat) 0.03125
Tray to Soups: (Tr_Sou) 0.01953125
Tray to Bread: (Tr_Bre) 0.01953125
Tray to Drinks: (Tr_Dri) 0.015625
Tray to Fruit: (Tr_Fru) 0.00390625
Tray to Kosher: (Tr_Kos) 0.00390625
Tray to Deli: (Tr_Del) 0.0
Tray to Desserts: (Tr_Des) 0.00390625

In [89]:
dest_list = list(survey_data.iloc[:,2:15].columns)
dest_list

['dest_1',
 'dest_2',
 'dest_3',
 'dest_4',
 'dest_5',
 'dest_6',
 'dest_7',
 'dest_8',
 'dest_9',
 'dest_10',
 'dest_11',
 'dest_12',
 'dest_13']

In [90]:
temp_station = ['Bread']
temp_dest = ["dest_1"]

In [102]:
# create empty data frame for results
results = pd.DataFrame()
results[0] = ["Station_name"] + station_list

In [103]:
results

                0
0    Station_name
1     Family Meal
2   Global Market
3           Grill
4         Special
5     Gluten Free
6       Salad Bar
7           Pizza
8           Vegan
9    Water/Juices
10          Soups
11          Bread
12         Drinks
13          Fruit
14         Kosher
15           Deli
16       Desserts

In [104]:
# have a separate column for each gl, gr, 
count = 1
for s in station_list:
    fa = 0
    gl = 0
    gr = 0
    sp = 0
    gf = 0
    sa = 0
    pi = 0
    ve = 0
    wa = 0
    so = 0
    br = 0
    dr = 0
    fr = 0
    ko = 0
    dl = 0
    de = 0
    # create counter for each station
    for d in dest_list:
        dest_num = int(d.split("_")[1]) # extract current destination number from column
        #print(s)
        if dest_num <13:
            next_dest = "dest_" + str(dest_num+1) # get next destination column name
            cond = survey_data[d] == s
            subset = survey_data[cond]
            fa = fa + sum(x=="Family Meal" for x in subset[next_dest])
            gl = gl + sum(x=="Global Market" for x in subset[next_dest])
            gr = gr + sum(x=="Grill" for x in subset[next_dest])
            sp = sp + sum(x=="Special" for x in subset[next_dest])
            gf = gf + sum(x=="Gluten Free" for x in subset[next_dest])
            sa = sa + sum(x=="Salad Bar" for x in subset[next_dest])
            pi = pi + sum(x=="Pizza" for x in subset[next_dest])
            ve = ve + sum(x=="Vegan" for x in subset[next_dest])
            wa = wa + sum(x=="Water/Juices" for x in subset[next_dest])
            so = so + sum(x=="Soups" for x in subset[next_dest])
            br = br + sum(x=="Bread" for x in subset[next_dest])
            dr = dr + sum(x=="Drinks" for x in subset[next_dest])
            fr = fr + sum(x=="Fruit" for x in subset[next_dest])
            ko = ko + sum(x=="Kosher" for x in subset[next_dest])
            dl = dl + sum(x=="Deli" for x in subset[next_dest])
            de = de + sum(x=="Desserts" for x in subset[next_dest])
            #print("Count of visits from " + s + " to other stations")
            #print(subset[next_dest].value_counts())
    start_station = s
    result = [s, fa, gl, gr, sp, gf, sa, pi, ve, wa, so, br, dr, fr, ko, dl, de]
    #temp_df = pd.DataFrame(result, columns=["Entry"])
    results[count] = result
    count = count + 1
results.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Station_name,Family Meal,Global Market,Grill,Special,Gluten Free,Salad Bar,Pizza,Vegan,Water/Juices,Soups,Bread,Drinks,Fruit,Kosher,Deli,Desserts
1,Family Meal,0,7,4,3,1,4,3,2,3,0,2,1,0,0,1,0
2,Global Market,26,0,9,1,3,3,2,1,1,2,0,1,2,0,0,0
3,Grill,10,17,0,3,2,7,4,2,1,2,1,1,3,0,1,0
4,Special,5,11,8,0,3,1,2,2,1,2,0,0,0,0,0,0

In [105]:
results.head(30)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Station_name,Family Meal,Global Market,Grill,Special,Gluten Free,Salad Bar,Pizza,Vegan,Water/Juices,Soups,Bread,Drinks,Fruit,Kosher,Deli,Desserts
1,Family Meal,0,7,4,3,1,4,3,2,3,0,2,1,0,0,1,0
2,Global Market,26,0,9,1,3,3,2,1,1,2,0,1,2,0,0,0
3,Grill,10,17,0,3,2,7,4,2,1,2,1,1,3,0,1,0
4,Special,5,11,8,0,3,1,2,2,1,2,0,0,0,0,0,0
5,Gluten Free,6,4,2,2,0,2,4,3,2,1,0,0,0,0,0,0
6,Salad Bar,8,8,25,13,7,0,5,4,3,5,3,2,1,0,3,1
7,Pizza,6,5,8,6,6,7,0,0,3,1,0,1,1,0,0,0
8,Vegan,3,1,3,2,3,2,2,0,0,0,2,0,0,0,0,0
9,Water/Juices,3,11,6,3,5,22,2,5,0,3,0,5,5,1,3,0
10,Soups,2,4,0,5,4,8,1,3,0,0,1,0,0,1,0,0
11,Bread,0,0,0,0,1,1,1,1,0,0,0,2,1,0,0,0
12,Drinks,2,8,15,5,3,9,8,1,8,10,0,0,7,0,2,1
13,Fruit,2,4,3,1,0,9,4,0,7,0,0,6,0,0,2,2
14,Kosher,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
15,Deli,1,1,1,1,2,3,3,0,3,1,0,4,0,0,0,1
16,Desserts,2,4,1,2,1,5,1,2,9,0,1,10,2,0,3,0

for s in temp_station:
    for d in temp_dest:
        cond = survey_data[d] == s 
        in survey_data.temp_dest
        survey_data[] [temp_dest].values:
            dest_num = int(d.split("_")[1]) # extract current destination number from column
            next_dest = "dest_" + str(dest_num+1) # get next destination column name
            #print(survey_data[next_dest].value_counts())
            print(next_dest)

In [55]:
survey_data[]

Index(['Family Meal', 'Global Market', 'Grill', 'Special', 'Gluten Free',
       'Salad Bar', 'Pizza', 'Vegan', 'Water/Juices', 'Soups', 'Bread',
       'Drinks', 'Fruit', 'Kosher', 'Desserts'],
      dtype='object')

In [57]:
print(dest_1_index.

<bound method IndexOpsMixin.value_counts of Index(['Family Meal', 'Global Market', 'Grill', 'Special', 'Gluten Free',
       'Salad Bar', 'Pizza', 'Vegan', 'Water/Juices', 'Soups', 'Bread',
       'Drinks', 'Fruit', 'Kosher', 'Desserts'],
      dtype='object')>

In [109]:
refill_yes = sum(x=="Yes" for x in survey_data.planning_for_refill)/survey_data.planning_for_refill.count()
refill_yes

0.6007905138339921

In [110]:
refill_no = sum(x=="No" for x in survey_data.planning_for_refill)/survey_data.planning_for_refill.count()
refill_no

0.39920948616600793

In [116]:
survey_data["refill_stations"].str.split(",")[0]

['Pizza']

In [124]:
survey_data["first_refill"] = survey_data["refill_stations"].str.split(",").str.get(0)

In [126]:
survey_data.head(10)

,grab_table,which_stations,dest_1,dest_2,dest_3,dest_4,dest_5,dest_6,dest_7,dest_8,dest_9,dest_10,dest_11,dest_12,dest_13,leave_line,leave_line_stations,planning_for_refill,refill_stations,first_refill
0,No,"Water/Juices,Drinks",Drinks,Water/Juices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Yes,Pizza,Pizza
1,Yes,"Global Market,Grill,Water/Juices,Drinks",Grill,Global Market,Drinks,Water/Juices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Yes,"Grill,Pizza",Grill
2,Yes,"Family Meal,Global Market,Salad Bar,Water/Juic...",Family Meal,Global Market,Salad Bar,Fruit,Water/Juices,Drinks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"Grill,Pizza",Yes,Desserts,Desserts
3,No,"Special,Salad Bar",Special,Salad Bar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Yes,Desserts,Desserts
4,Yes,"Family Meal,Pizza,Gluten Free,Water/Juices,Des...",Water/Juices,Gluten Free,Pizza,Family Meal,Desserts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN
5,No,"Grill,Water/Juices,Fruit",Grill,Fruit,Water/Juices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN
6,No,"Grill,Pizza,Water/Juices",Grill,Water/Juices,Pizza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Family Meal,No,NaN,NaN
7,No,"Family Meal,Grill,Drinks",Family Meal,Grill,Drinks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN
8,No,"Family Meal,Grill,Salad Bar",Grill,Family Meal,Salad Bar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"Family Meal,Grill,Salad Bar",Yes,"Family Meal,Grill,Salad Bar",Family Meal
9,Yes,"Family Meal,Global Market,Grill,Salad Bar,Wate...",Salad Bar,Grill,Family Meal,Global Market,Water/Juices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN

Desserts         31
Family Meal      22
Drinks           18
Pizza            14
Water/Juices     14
Grill            14
Global Market    11
Fruit             8
Salad Bar         7
Special           6
Soups             5
Gluten Free       1
Deli              1
Name: first_refill, dtype: int64

152